### ISSUE TITLE
Get error git error after update to 3.1

### ISSUE THREAD

**Issue by rudvfaden** [wbond/package_control#996]
After upgrading to 3.1 i get the following error when i try to upgrade packages

```
Error executing: /usr/bin/git symbolic-ref -q HEAD
```

I have git installed and it in my system path. I tried to purge en reinstall but got the same error on installation. The following is from the console log.

```python
AttributeError: 'bool' object has no attribute 'replace'

error: Package Control

Error executing: /usr/bin/git symbolic-ref -q HEAD



VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
Exception in thread Thread-24:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.upgrade_package_command in /Users/rudfaden/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 53, in run
  File "package_control.package_installer in /Users/rudfaden/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 100, in make_package_list
  File "package_control.upgraders.git_upgrader in /Users/rudfaden/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 103, in incoming
  File "package_control.upgraders.git_upgrader in /Users/rudfaden/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 59, in get_working_copy_info
AttributeError: 'bool' object has no attribute 'replace'
```

**Comment by wbond** [comment]
Looks to be a duplicate of #995
