### ISSUE TITLE
PC 4.0.0-beta3: Package Control: The library "package_setting_context" is not available for Python 3.8

### ISSUE THREAD

**Issue by jfcherng** [wbond/package_control#1643]
After updating to 4.0.0-beta3 (from beta2), I get this error in ST console during starting.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 944, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\ColorHelper.sublime-package\ch_preview.py", line 682, in on_activated_async
    view.window().run_command('color_helper_preview', {"clear": False, "force": True})
AttributeError: 'NoneType' object has no attribute 'run_command'
Package Control: The library "package_setting_context" is not available for Python 3.8
```

**Comment by deathaxe** [comment]
> AttributeError: 'NoneType' object has no attribute 'run_command'

I've seen ColorHelper throwing `NoneType` errors various times, already. Haven't had time to dig into it, but I doubt there's something Package Control could do to prevent it. 

> Package Control: The library "package_setting_context" is not available for Python 3.8

The message indicates at least one package running on python 3.8 plugin_host, which requests `package_setting_context` dependency.

Nothing to be concerned about. PC just shows the result of checking missing libraries at start.

While Package Control client can handle python 3.8 dependencies, packagecontrol.io requires update to ship channel_v4.json files with required meta data.

**Comment by jfcherng** [comment]
This looks good at this moment. Sorry for the false alram 😓
